# Generated by Django 4.2.14 on 2024-07-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_patientprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='blood_group',
        ),
    ]
