# Generated by Django 4.2.14 on 2024-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_patientprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(choices=[('Not Selected', 'Not Selected'), ('ARH+', 'ARH+'), ('ARH-', 'ARH-'), ('BRH+', 'BRH+'), ('BRH-', 'BRH-'), ('ABRH+', 'ABRH+'), ('ABRH-', 'ABRH-'), ('0RH+', '0RH+'), ('0RH-', '0RH-')], default='Not Selected', max_length=13),
        ),
    ]
